POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhha2thbWFyIiwiaWQiOiI1YjlmNjA4NTdkODc5ODQwMjg5ZTgzNjQiLCJpYXQiOjE1MzcxNzE2NDF9.CenAdq7bXb3nOJ8UfGQYD6Cbf5M9yXHqdZqW-wo1Imo

{
	"title": "Testiä - again...",
	"author": "Marko A.K. Hakkarainen",
	"url": "https://www.MAKhakkarainen.fi",
	"likes": 6,
	"userId": "5b9f60857d879840289e8364"
}